import Vue from "vue";
import CardSlider from "@/components/base/cardSlider";
import RangeSlider from "@/components/base/rangeSlider";
import Iconfont from "@/components/base/iconfont";
import SearchPanel from "@/components/base/searchPanel";
import SvgIcon from "@/components/base/svg";
import Overlayer from "@/components/base/overlayer";
import Toast from "@/components/base/toast";
import AsyncComponent from "@/components/base/asyncComponent";
import {XTextField, XForm} from "@/components/base/form";

Vue.use(CardSlider);
Vue.use(RangeSlider);
Vue.use(Iconfont);
Vue.use(SearchPanel);
Vue.use(SvgIcon);
Vue.use(Overlayer);
Vue.use(Toast);
Vue.use(AsyncComponent);
Vue.use(XTextField);
Vue.use(XForm);
